//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PARKOMAT
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Автомобиль.
    /// </summary>
    // *** Start programmer edit section *** (Автомобиль CustomAttributes)

    // *** End programmer edit section *** (Автомобиль CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АвтомобильE", new string[] {
            "ГосНомер as \'Гос номер\'",
            "Водитель as \'Водитель\'",
            "Водитель.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Водитель.ФИО"})]
    [MasterViewDefineAttribute("АвтомобильE", "Водитель", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class Автомобиль : ICSSoft.STORMNET.DataObject
    {
        
        private string fГосНомер;
        
        private IIS.PARKOMAT.Водитель fВодитель;
        
        private IIS.PARKOMAT.Услуга fУслуга;
        
        // *** Start programmer edit section *** (Автомобиль CustomMembers)

        // *** End programmer edit section *** (Автомобиль CustomMembers)

        
        /// <summary>
        /// ГосНомер.
        /// </summary>
        // *** Start programmer edit section *** (Автомобиль.ГосНомер CustomAttributes)

        // *** End programmer edit section *** (Автомобиль.ГосНомер CustomAttributes)
        [StrLen(255)]
        public virtual string ГосНомер
        {
            get
            {
                // *** Start programmer edit section *** (Автомобиль.ГосНомер Get start)

                // *** End programmer edit section *** (Автомобиль.ГосНомер Get start)
                string result = this.fГосНомер;
                // *** Start programmer edit section *** (Автомобиль.ГосНомер Get end)

                // *** End programmer edit section *** (Автомобиль.ГосНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автомобиль.ГосНомер Set start)

                // *** End programmer edit section *** (Автомобиль.ГосНомер Set start)
                this.fГосНомер = value;
                // *** Start programmer edit section *** (Автомобиль.ГосНомер Set end)

                // *** End programmer edit section *** (Автомобиль.ГосНомер Set end)
            }
        }
        
        /// <summary>
        /// Автомобиль.
        /// </summary>
        // *** Start programmer edit section *** (Автомобиль.Водитель CustomAttributes)

        // *** End programmer edit section *** (Автомобиль.Водитель CustomAttributes)
        [PropertyStorage(new string[] {
                "Водитель"})]
        [NotNull()]
        public virtual IIS.PARKOMAT.Водитель Водитель
        {
            get
            {
                // *** Start programmer edit section *** (Автомобиль.Водитель Get start)

                // *** End programmer edit section *** (Автомобиль.Водитель Get start)
                IIS.PARKOMAT.Водитель result = this.fВодитель;
                // *** Start programmer edit section *** (Автомобиль.Водитель Get end)

                // *** End programmer edit section *** (Автомобиль.Водитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автомобиль.Водитель Set start)

                // *** End programmer edit section *** (Автомобиль.Водитель Set start)
                this.fВодитель = value;
                // *** Start programmer edit section *** (Автомобиль.Водитель Set end)

                // *** End programmer edit section *** (Автомобиль.Водитель Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.PARKOMAT.Услуга.
        /// </summary>
        // *** Start programmer edit section *** (Автомобиль.Услуга CustomAttributes)

        // *** End programmer edit section *** (Автомобиль.Услуга CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Услуга"})]
        public virtual IIS.PARKOMAT.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (Автомобиль.Услуга Get start)

                // *** End programmer edit section *** (Автомобиль.Услуга Get start)
                IIS.PARKOMAT.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (Автомобиль.Услуга Get end)

                // *** End programmer edit section *** (Автомобиль.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автомобиль.Услуга Set start)

                // *** End programmer edit section *** (Автомобиль.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (Автомобиль.Услуга Set end)

                // *** End programmer edit section *** (Автомобиль.Услуга Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АвтомобильE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвтомобильE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвтомобильE", typeof(IIS.PARKOMAT.Автомобиль));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Автомобиль.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfАвтомобиль CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfАвтомобиль CustomAttributes)
    public class DetailArrayOfАвтомобиль : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.PARKOMAT.DetailArrayOfАвтомобиль members)

        // *** End programmer edit section *** (IIS.PARKOMAT.DetailArrayOfАвтомобиль members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Автомобиль by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Автомобиль.
        /// </summary>
        public DetailArrayOfАвтомобиль(IIS.PARKOMAT.Услуга fУслуга) : 
                base(typeof(Автомобиль), ((ICSSoft.STORMNET.DataObject)(fУслуга)))
        {
        }
        
        public IIS.PARKOMAT.Автомобиль this[int index]
        {
            get
            {
                return ((IIS.PARKOMAT.Автомобиль)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.PARKOMAT.Автомобиль dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
