//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.PARKOMAT
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Паркомат.
    /// </summary>
    // *** Start programmer edit section *** (Паркомат CustomAttributes)

    // *** End programmer edit section *** (Паркомат CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПаркоматE", new string[] {
            "НомерПарк as \'Номер паркомата\'",
            "ВремяОплаты as \'Время оплаты\'",
            "ДатаОплаты as \'Дата оплаты\'",
            "СтатОпл as \'Статус оплаты\'",
            "ВремяОкон as \'Время окончания\'",
            "ДатаОкон as \'Дата окончания\'",
            "Терминал as \'Терминал\'",
            "Терминал.НомерТер as \'Номер терминала\'"}, Hidden=new string[] {
            "Терминал.НомерТер"})]
    [AssociatedDetailViewAttribute("ПаркоматE", "Запись", "ЗаписьE", true, "", "Запись", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПаркоматE", "Терминал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерТер")]
    [View("ПаркоматL", new string[] {
            "НомерПарк as \'Номер паркомата\'",
            "ВремяОплаты as \'Время оплаты\'",
            "ДатаОплаты as \'Дата оплаты\'",
            "СтатОпл as \'Статус оплаты\'",
            "ВремяОкон as \'Время окончания\'",
            "ДатаОкон as \'Дата окончания\'",
            "Терминал.НомерТер as \'Номер терминала\'"})]
    public class Паркомат : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерПарк;
        
        private string fВремяОплаты;
        
        private System.DateTime fДатаОплаты;
        
        private IIS.PARKOMAT.Оплата fСтатОпл;
        
        private string fВремяОкон;
        
        private System.DateTime fДатаОкон;
        
        private IIS.PARKOMAT.Терминал fТерминал;
        
        private IIS.PARKOMAT.DetailArrayOfЗапись fЗапись;
        
        // *** Start programmer edit section *** (Паркомат CustomMembers)

        // *** End programmer edit section *** (Паркомат CustomMembers)

        
        /// <summary>
        /// ВремяОкон.
        /// </summary>
        // *** Start programmer edit section *** (Паркомат.ВремяОкон CustomAttributes)

        // *** End programmer edit section *** (Паркомат.ВремяОкон CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяОкон
        {
            get
            {
                // *** Start programmer edit section *** (Паркомат.ВремяОкон Get start)

                // *** End programmer edit section *** (Паркомат.ВремяОкон Get start)
                string result = this.fВремяОкон;
                // *** Start programmer edit section *** (Паркомат.ВремяОкон Get end)

                // *** End programmer edit section *** (Паркомат.ВремяОкон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Паркомат.ВремяОкон Set start)

                // *** End programmer edit section *** (Паркомат.ВремяОкон Set start)
                this.fВремяОкон = value;
                // *** Start programmer edit section *** (Паркомат.ВремяОкон Set end)

                // *** End programmer edit section *** (Паркомат.ВремяОкон Set end)
            }
        }
        
        /// <summary>
        /// ВремяОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Паркомат.ВремяОплаты CustomAttributes)

        // *** End programmer edit section *** (Паркомат.ВремяОплаты CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Паркомат.ВремяОплаты Get start)

                // *** End programmer edit section *** (Паркомат.ВремяОплаты Get start)
                string result = this.fВремяОплаты;
                // *** Start programmer edit section *** (Паркомат.ВремяОплаты Get end)

                // *** End programmer edit section *** (Паркомат.ВремяОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Паркомат.ВремяОплаты Set start)

                // *** End programmer edit section *** (Паркомат.ВремяОплаты Set start)
                this.fВремяОплаты = value;
                // *** Start programmer edit section *** (Паркомат.ВремяОплаты Set end)

                // *** End programmer edit section *** (Паркомат.ВремяОплаты Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкон.
        /// </summary>
        // *** Start programmer edit section *** (Паркомат.ДатаОкон CustomAttributes)

        // *** End programmer edit section *** (Паркомат.ДатаОкон CustomAttributes)
        public virtual System.DateTime ДатаОкон
        {
            get
            {
                // *** Start programmer edit section *** (Паркомат.ДатаОкон Get start)

                // *** End programmer edit section *** (Паркомат.ДатаОкон Get start)
                System.DateTime result = this.fДатаОкон;
                // *** Start programmer edit section *** (Паркомат.ДатаОкон Get end)

                // *** End programmer edit section *** (Паркомат.ДатаОкон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Паркомат.ДатаОкон Set start)

                // *** End programmer edit section *** (Паркомат.ДатаОкон Set start)
                this.fДатаОкон = value;
                // *** Start programmer edit section *** (Паркомат.ДатаОкон Set end)

                // *** End programmer edit section *** (Паркомат.ДатаОкон Set end)
            }
        }
        
        /// <summary>
        /// ДатаОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Паркомат.ДатаОплаты CustomAttributes)

        // *** End programmer edit section *** (Паркомат.ДатаОплаты CustomAttributes)
        public virtual System.DateTime ДатаОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Паркомат.ДатаОплаты Get start)

                // *** End programmer edit section *** (Паркомат.ДатаОплаты Get start)
                System.DateTime result = this.fДатаОплаты;
                // *** Start programmer edit section *** (Паркомат.ДатаОплаты Get end)

                // *** End programmer edit section *** (Паркомат.ДатаОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Паркомат.ДатаОплаты Set start)

                // *** End programmer edit section *** (Паркомат.ДатаОплаты Set start)
                this.fДатаОплаты = value;
                // *** Start programmer edit section *** (Паркомат.ДатаОплаты Set end)

                // *** End programmer edit section *** (Паркомат.ДатаОплаты Set end)
            }
        }
        
        /// <summary>
        /// НомерПарк.
        /// </summary>
        // *** Start programmer edit section *** (Паркомат.НомерПарк CustomAttributes)

        // *** End programmer edit section *** (Паркомат.НомерПарк CustomAttributes)
        public virtual int НомерПарк
        {
            get
            {
                // *** Start programmer edit section *** (Паркомат.НомерПарк Get start)

                // *** End programmer edit section *** (Паркомат.НомерПарк Get start)
                int result = this.fНомерПарк;
                // *** Start programmer edit section *** (Паркомат.НомерПарк Get end)

                // *** End programmer edit section *** (Паркомат.НомерПарк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Паркомат.НомерПарк Set start)

                // *** End programmer edit section *** (Паркомат.НомерПарк Set start)
                this.fНомерПарк = value;
                // *** Start programmer edit section *** (Паркомат.НомерПарк Set end)

                // *** End programmer edit section *** (Паркомат.НомерПарк Set end)
            }
        }
        
        /// <summary>
        /// СтатОпл.
        /// </summary>
        // *** Start programmer edit section *** (Паркомат.СтатОпл CustomAttributes)

        // *** End programmer edit section *** (Паркомат.СтатОпл CustomAttributes)
        public virtual IIS.PARKOMAT.Оплата СтатОпл
        {
            get
            {
                // *** Start programmer edit section *** (Паркомат.СтатОпл Get start)

                // *** End programmer edit section *** (Паркомат.СтатОпл Get start)
                IIS.PARKOMAT.Оплата result = this.fСтатОпл;
                // *** Start programmer edit section *** (Паркомат.СтатОпл Get end)

                // *** End programmer edit section *** (Паркомат.СтатОпл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Паркомат.СтатОпл Set start)

                // *** End programmer edit section *** (Паркомат.СтатОпл Set start)
                this.fСтатОпл = value;
                // *** Start programmer edit section *** (Паркомат.СтатОпл Set end)

                // *** End programmer edit section *** (Паркомат.СтатОпл Set end)
            }
        }
        
        /// <summary>
        /// Паркомат.
        /// </summary>
        // *** Start programmer edit section *** (Паркомат.Терминал CustomAttributes)

        // *** End programmer edit section *** (Паркомат.Терминал CustomAttributes)
        [PropertyStorage(new string[] {
                "Терминал"})]
        [NotNull()]
        public virtual IIS.PARKOMAT.Терминал Терминал
        {
            get
            {
                // *** Start programmer edit section *** (Паркомат.Терминал Get start)

                // *** End programmer edit section *** (Паркомат.Терминал Get start)
                IIS.PARKOMAT.Терминал result = this.fТерминал;
                // *** Start programmer edit section *** (Паркомат.Терминал Get end)

                // *** End programmer edit section *** (Паркомат.Терминал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Паркомат.Терминал Set start)

                // *** End programmer edit section *** (Паркомат.Терминал Set start)
                this.fТерминал = value;
                // *** Start programmer edit section *** (Паркомат.Терминал Set end)

                // *** End programmer edit section *** (Паркомат.Терминал Set end)
            }
        }
        
        /// <summary>
        /// Паркомат.
        /// </summary>
        // *** Start programmer edit section *** (Паркомат.Запись CustomAttributes)

        // *** End programmer edit section *** (Паркомат.Запись CustomAttributes)
        public virtual IIS.PARKOMAT.DetailArrayOfЗапись Запись
        {
            get
            {
                // *** Start programmer edit section *** (Паркомат.Запись Get start)

                // *** End programmer edit section *** (Паркомат.Запись Get start)
                if ((this.fЗапись == null))
                {
                    this.fЗапись = new IIS.PARKOMAT.DetailArrayOfЗапись(this);
                }
                IIS.PARKOMAT.DetailArrayOfЗапись result = this.fЗапись;
                // *** Start programmer edit section *** (Паркомат.Запись Get end)

                // *** End programmer edit section *** (Паркомат.Запись Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Паркомат.Запись Set start)

                // *** End programmer edit section *** (Паркомат.Запись Set start)
                this.fЗапись = value;
                // *** Start programmer edit section *** (Паркомат.Запись Set end)

                // *** End programmer edit section *** (Паркомат.Запись Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПаркоматE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПаркоматE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПаркоматE", typeof(IIS.PARKOMAT.Паркомат));
                }
            }
            
            /// <summary>
            /// "ПаркоматL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПаркоматL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПаркоматL", typeof(IIS.PARKOMAT.Паркомат));
                }
            }
        }
    }
}
